# - name:create the iptables include file to be run at reboot 
---
- stat:
    path: $HOME/iptab.sh
  register: iptm
- file:
    path: $HOME/iptab.sh
    state: touch
    mode: 0777
  when:
    - iptm.stat.exists == False
- blockinfile:
    dest: $HOME/iptab.sh
    mode: u+rwx
    block: |
      sudo iptables -P FORWARD ACCEPT
  when:
   - iptm.stat.exists == False
- stat:
    path: /etc/init.d/iptab.sh
  become: sudo
  register: itm
- command: sudo cp $HOME/iptab.sh /etc/init.d/
  when: itm.stat.exists == False
- command: sudo update-rc.d iptab.sh defaults
  when: itm.stat.exists == False
